version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_package:
    jobs:
      - maven/install
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
